version: '2'
services:
  taroco-registry:
    build:
      context: ./
      dockerfile: Dockerfile-registry
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /data/logs/taroco-registry/:/logs/taroco-registry/
    networks:
      - taroco

  taroco-config:
    links:
      - taroco-registry
    build:
      context: ./
      dockerfile: Dockerfile-config
    restart: always
    environment:
      - EUREKA_SERVER_HOST=taroco-registry
    depends_on:
      - taroco-registry
    volumes:
      - /data/logs/taroco-config/:/logs/taroco-config/
    networks:
      - taroco

networks:
  taroco:
